### ISSUE TITLE
Hey Megan! We Have Issues

### ISSUE THREAD

**Issue by idbachli** [epid8060fall2019/MeganBeaudry-Introduction#1]
Nice Introduction. 

Sorry for the late reply, as Dr. Handel mentioned I think a lot of people thought this was due Today. Anyhow, I couldn't find too many issues with your Introduction Page (It was very nice), so I guess my issue is maybe add your best Marathon ever in terms of completion time? I think that would be a cool fact to include. 

Thanks!

**Comment by MeganSarah** [comment]
Hi Ian,

I have included the fact!

Best,
Megan
